version: "3.7"
services:
  topupmama_app:
    build:
      args:
        user: acidicyemi
        uid: 1000
      context: ./
      dockerfile: ./.docker/php/Dockerfile
    image: topupmama_app
    container_name: topupmama_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - topupmama

  topupmama_mysql:
    image: mysql:8.0.26
    container_name: topupmama_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_PORT_EXTERNAL?err}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD?err}
      MYSQL_PASSWORD: ${DB_PASSWORD?err}
    networks:
      - topupmama
    volumes:
      - .docker/mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - .docker/mysql/my.conf:/etc/my.cnf

  nginx:
    image: nginx:alpine
    container_name: topupmama_nginx
    restart: unless-stopped
    depends_on:
      - topupmama_mysql
      - topupmama_app
    ports:
      - ${APP_PORT?err}:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - topupmama

networks:
  topupmama:
    driver: bridge