name: Deploy Application

on:
  push:
    branches: [master]

jobs:
  create-deployment-artifacts:
    name: Create Deployment Artifacts

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@master
        with:
          php-version: "7.4"

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit

      - name: Create deployment Artifact
        # -czf -c for create a new archive -z for g compression -f for output in a file
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: tar -czf "${GITHUB_SHA}".tar.gz  --directory=/ --exclude=*.git

      - name: Store Artifact for distribution
        uses: actions/upload-artifact@v2
        with:
          name: topupmama-app
          path: ${{ github.sha }}.tar.gz

  push-app-to-server:
    runs-on: ubuntu-latest

    needs: create-deployment-artifacts

    steps:
      - name: setup download artifact actions
        uses: actions/download-artifact@v2
        with:
          name: topupmama-app

      - name: Upload Build
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: ${{ github.sha }}.tar.gz
          target: "/var/www/topupmama/artifacts"

      - name: Extract Archieve and create directories
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          envs: GITHUB_SHA
          script: |
            mkdir -p /var/www/topupmama/releases/${GITHUB_SHA}
            tar xzf /var/www/topupmama/artifacts/${GITHUB_SHA}.tar.gz -C /var/www/topupmama/releases/${GITHUB_SHA}

            rm -rf /var/www/topupmama/releases/${GITHUB_SHA}/storage
            mkdir -p  /var/www/topupmama/storage/{app,public,framework,logs}
            mkdir -p  /var/www/topupmama/storage/framework/{cache,sessions,testing,views}
            mkdir -p  /var/www/topupmama/storage/framework/cache/data
            chmod -R 0777  /var/www/topupmama/storage
